#!/usr/bin/env bash

echo "Running initial apply..."
chezmoi apply

echo "Watching './home' for changes..."

fswatch -0 home | while read -d "" path
  do    
    echo "Applying - $path"
    chezmoi apply "$@"
  done