tap "homebrew/bundle"
tap "koekeishiya/formulae"
tap "hashicorp/tap"
tap "cirruslabs/cli"

cask "raycast"
cask "hammerspoon"
cask "karabiner-elements"

brew "cirruslabs/cli/tart"
# brew "koekeishiya/formulae/yabai"
# brew "koekeishiya/formulae/skhd"

cask "visual-studio-code"
vscode "jnoortheen.nix-ide"
vscode "sumneko.lua"
vscode "timonwong.shellcheck"
vscode "dbaeumer.vscode-eslint"
vscode "ms-playwright.playwright"
vscode "vitest.explorer"
vscode "vue.volar"
# vscode "WallabyJs.wallaby-vscode"
# vscode "WallabyJs.quokka-vscode"
vscode "andrewbranch.vscode-tsserver-debug"
vscode "hashicorp.terraform"
vscode "ms-azuretools.vscode-docker"
vscode "yoavbls.pretty-ts-errors"
vscode "bierner.markdown-mermaid"
vscode "christian-kohler.path-intellisense"

# vscode extensions
vscode "ms-vscode.extension-test-runner"

# esbuild
vscode "connor4312.esbuild-problem-matchers"

# python
vscode "ms-python.python"
vscode "ms-python.debugpy"
vscode "ms-python.vscode-pylance"

vscode "ms-vsliveshare.vsliveshare"
vscode "vercel.turbo-vsc"

cask "google-cloud-sdk"


cask "hashicorp/tap/hashicorp-vagrant"
cask "parallels-virtualization-sdk"

brew "temporal"
