tap "koekeishiya/formulae"
# tap "hashicorp/tap"
# tap "cirruslabs/cli"

cask "ghostty"
cask "raycast"

brew "yabai"
cask "hammerspoon"
cask "karabiner-elements"

# brew "cirruslabs/cli/tart"
# brew "koekeishiya/formulae/yabai"


# 'gettext' commands, e.g. 'msgcat'
brew "gettext"

cask "visual-studio-code"
vscode "jnoortheen.nix-ide"
vscode "sumneko.lua"
vscode "timonwong.shellcheck"
vscode "dbaeumer.vscode-eslint"
vscode "ms-playwright.playwright"
vscode "vitest.explorer"
vscode "vue.volar"
# vscode "WallabyJs.wallaby-vscode"
# vscode "WallabyJs.quokka-vscode"
vscode "andrewbranch.vscode-tsserver-debug"
vscode "hashicorp.terraform"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "bierner.markdown-mermaid"
vscode "christian-kohler.path-intellisense"

# Make TS error prettier
vscode "yoavbls.pretty-ts-errors" 
# Hide original, ugly errors (instructions included)
# https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css
vscode "be5invis.vscode-custom-css" 
vscode "bierner.docs-view"

# vscode extensions
vscode "ms-vscode.extension-test-runner"

# esbuild
vscode "connor4312.esbuild-problem-matchers"

# python
vscode "ms-python.python"
vscode "ms-python.debugpy"
vscode "ms-python.vscode-pylance"

vscode "ms-vsliveshare.vsliveshare"

# flutter
vscode "dart-code.dart-code"
vscode "dart-code.flutter"

vscode "vercel.turbo-vsc"

vscode "casualjim.gotemplate"
vscode "redhat.vscode-yaml"

cask "gcloud-cli"


#cask "hashicorp/tap/hashicorp-vagrant"
#cask "parallels-virtualization-sdk"

brew "temporal"

cask "1password-cli"

brew "zsh-completions"

# holvi/appenzeller

brew "pkg-config"
brew "cairo"
brew "pango"
brew "libpng"
brew "jpeg"
brew "giflib"
brew "librsvg"


cask "google-chrome"

# Postgres
brew "postgresql"
cask "pgadmin4"

brew "pnpm"

brew "atmos"
brew "opentofu"

brew "awscli"


# Docker
# cask "docker"