tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "koekeishiya/formulae"

cask "raycast"
cask "hammerspoon"

brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"

cask "visual-studio-code"
vscode "jnoortheen.nix-ide"
vscode "sumneko.lua"

cask "hashicorp/tap/hashicorp-vagrant"
cask "parallels-virtualization-sdk"