#!/usr/bin/env bash

export GITHUB_USERNAME=martaver
export EDITOR="code --wait"

get_sha1() {
    sha1sum "$1" | head -c 40
}

get_test() {
    yq 'keys[]' < ~/test.yaml
}

source ~/.yabai/.fns
source ~/.config/kitty/kitty-quake
