#!/usr/bin/env bash

export GITHUB_USERNAME=martaver
export EDITOR="code --wait"

export NVM_LAZY=1

get_sha1() {
    sha1sum "$1" | head -c 40
}

get_test() {
    yq 'keys[]' < ~/test.yaml
}

source ~/.yabai/.fns
source ~/.config/kitty/kitty-quake


# export GOKU_EDN_CONFIG_FILE=~/.config/karabiner/karabiner.edn
