#!/usr/bin/env sh

# Enable the scripting addition
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555

# # Mouse support
# yabai -m config mouse_modifier               alt
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off

# float settings windows
yabai -m rule --add app='^Parallels Desktop$' manage=off
yabai -m rule --add app='^System Settings$' manage=off
yabai -m rule --add title='^Control Center$' manage=off


# YFL="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
# YFL="./Users/sebastian.nemeth/.yabai/bin/yb_focus_last"
INSTALL="PATH=/Users/sebastian.nemeth/.yabai/bin:${PATH}"

# Focus on recent/first window after closing/minimising the current one

# Todo: figure out how to set PATHS for the posix shell that yabai executes its scripts in
yabai -m signal --add event=window_destroyed action="$INSTALL && yb_focus_last"
yabai -m signal --add event=window_minimized action="$INSTALL && yb_focus_last"
yabai -m signal --add event=application_terminated action="$INSTALL && yb_focus_last"
yabai -m signal --add event=application_hidden action="$INSTALL && yb_focus_last"
