#!/usr/bin/env sh

# Syncthing
# brew install --cask syncthing

# sha1sum etc
brew install coreutils

# Skhd (key bindings)
brew install koekeishiya/formulae/skhd
brew services start skhd

# Yabai (window tiling)
brew install koekeishiya/formulae/yabai
brew services start yabai

# YQ
brew install yq

# Kitty
brew install --cask kitty

# chezmoi
brew install chezmoi

# github
brew install gh

# fswatch
brew install fswatch

# Install starship prompt
brew install starship

# Install goku for making karabiner configs
brew install yqrashawn/goku/goku
brew services start yqrashawn/goku/goku

# Java
brew install java
