#!/usr/bin/env bash

export GITHUB_USERNAME=martaver

# Uses VSCode as default text editor.
# A dir opened from terminal will block until VSCode closes.
# A file opened from terminal will block until the file's editor in VSCode closes.
export EDITOR="code --wait"

get_sha1() {
    sha1sum "$1" | head -c 40
}

get_test() {
    yq 'keys[]' < ~/test.yaml
}

source ~/.yabai/.fns
source ~/.config/kitty/kitty-quake


# export GOKU_EDN_CONFIG_FILE=~/.config/karabiner/karabiner.edn

#
# rust
#
. "$HOME/.cargo/env"