#!/usr/bin/env sh

yb_focus()      { 
    yabai -m window --focus $1 
}

yb_move()       { 
    yabai -m window --swap $1 || $(yabai -m window --display $1; yabai -m display --focus $1) 
}

yb_insert()     { 
    yabai -m window --insert $1
}

sz=100

yb_grow() {
    case $1 in
        top)        yabai -m window --resize top:0:-$sz ;;
        bottom)     yabai -m window --resize bottom:0:$sz ;;
        left)       yabai -m window --resize left:-$sz:0 ;;
        right)      yabai -m window --resize right:$sz:0 ;;
    esac
}

yb_shrink() {
    case $1 in
        top)        yabai -m window --resize top:0:$sz ;;
        bottom)     yabai -m window --resize bottom:0:-$sz ;;
        left)       yabai -m window --resize left:$sz:0 ;;
        right)      yabai -m window --resize right:-$sz:0 ;;
    esac
}

# change focus : alt - ctrl
#    - hjkl
#    - between screens
#    - between workspaces

# move window : alt - shift - ctrl
#    - hjkl
#    - between screens
#    - between workspaces

# resize window: 

# insert window: 
# cancel insert:

get_window() {
    yabai -m query --windows | title="$1" yq 'map(select(.title == env(title))).0'
}