# Configuration reference: https://starship.rs/config/#prompt

# Which is equivalent to
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
"""