#!/usr/bin/env bash

. ./utils

prepare


# ###############################################################################
# # Sublime Text                                                                #
# ###############################################################################

# # Install Sublime Text settings
# cp -r init/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings 2> /dev/null



# kill_apps "Sublime Text"