#!/usr/bin/env bash

. ./utils

prepare


###############################################################################
# Photos
###############################################################################

# Prevent Photos from opening automatically when devices are plugged in
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true




kill_apps "Photos"