#!/usr/bin/env bash

. ./utils

prepare




# ###############################################################################
# # Opera & Opera Developer                                                     #
# ###############################################################################

# # Expand the print dialog by default
# defaults write com.operasoftware.Opera PMPrintingExpandedStateForPrint2 -boolean true
# defaults write com.operasoftware.OperaDeveloper PMPrintingExpandedStateForPrint2 -boolean true




# kill_apps "Opera"