#!/usr/bin/env bash

. ./utils

prepare
get_sudo

###############################################################################
# Energy saving                                                               #
###############################################################################

# Enable lid wakeup
sudo pmset -a lidwake 1

# Restart automatically on power loss
sudo pmset -a autorestart 1

# Restart automatically if the computer freezes
# sudo systemsetup -setrestartfreeze on

# Sleep the display after 15 minutes
sudo pmset -b displaysleep 15

# Don't sleep the display while charging
sudo pmset -c displaysleep 0

# Disable machine sleep while charging
sudo pmset -c sleep 0

# Set machine sleep to 5 minutes on battery
sudo pmset -b sleep 5

# Set standby delay to 24 hours (default is 1 hour)
sudo pmset -a standbydelay 86400

# # Never go into computer sleep mode
# sudo systemsetup -setcomputersleep Off > /dev/null

# # Hibernation mode
# # 0: Disable hibernation (speeds up entering sleep mode)
# # 3: Copy RAM to disk so the system state can still be restored in case of a
# #    power failure.
# sudo pmset -a hibernatemode 0

# # Remove the sleep image file to save disk space
# sudo rm /private/var/vm/sleepimage
# # Create a zero-byte file instead…
# sudo touch /private/var/vm/sleepimage
# # …and make sure it can’t be rewritten
# sudo chflags uchg /private/var/vm/sleepimage