#!/usr/bin/env bash

. ./utils

prepare


###############################################################################
# Calendar
###############################################################################

# Enable the debug menu in iCal (pre-10.8)
defaults write com.apple.iCal IncludeDebugMenu -bool true


kill_apps "Calendar"