#!/usr/bin/env bash

. ./utils

prepare
get_sudo




###############################################################################
# Dashboard
###############################################################################



# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true


# Enable Dashboard dev mode (allows keeping widgets on the desktop)
defaults write com.apple.dashboard devmode -bool true


kill_apps "Dock"