#!/usr/bin/env bash

. ./utils

prepare


###############################################################################
# Address Book
###############################################################################

# Enable the debug menu in Address Book
defaults write com.apple.addressbook ABShowDebugMenu -bool true



kill_apps "Address Book"